services:
    nginx:
        extends:
            file: ./app/docker-compose.yml
            service: nginx

    php-fpm:
        extends:
            file: ./app/docker-compose.yml
            service: php-fpm

    mysql:
        extends:
            file: ./mysql/docker-compose.yml
            service: mysql

    load-balancer:
        image: nginx:alpine
        container_name: load-balancer
        volumes:
            - ./app:/var/www/us/site
            - ./load-balancer/load-balancer.conf:/etc/nginx/nginx.conf:ro
            - ./load-balancer/log:/var/log/nginx
        networks:
            - common
        ports:
            - 3000:80

    clickhouse:
        extends:
            service: clickhouse
            file: ./clickhouse/docker-compose.yml

networks:
    common:
        external: true